version: "3.8"
services:
  mysql:
    image: mysql:8
    container_name: grip-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gripdb
    ports:
      - "3306:3306"
